name: Docker Sync

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:


jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        logout: false

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        skopeo copy docker://docker.io/nginx:latest docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/nginx:latest
