name: Docker Sync

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # 允许您从“操作”选项卡手动运行此工作流
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3.7.1

    - name: Login to Docker Hub
      uses: docker/login-action@v3.3.0
      with:
        registry: registry.cn-hangzhou.aliyuncs.com
        username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
        password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}
        logout: true

    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        # Nginx
        skopeo copy docker://docker.io/nginx:latest docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/nginx:latest
        
        # PHP
        skopeo copy docker://docker.io/php:latest docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/php:latest
        skopeo copy docker://docker.io/php:8.3.0-fpm docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/php:8.3.0-fpm
        skopeo copy docker://docker.io/php:8.3.0-fpm-alpine docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/php:8.3.0-fpm-alpine
        
        # PHP integration
        skopeo copy docker://docker.io/suyar/php:8.3-integration docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/suyar_php:8.3-integration
        
        # PHP alpine integration
        skopeo copy docker://docker.io/suyar/php:8.3-alpine-integration docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/suyar_php:8.3-alpine-integration
        
        # Composer
        skopeo copy docker://docker.io/composer:latest docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/composer:latest
        
        # Mysql
        skopeo copy docker://docker.io/mysql:latest docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/mysql:latest
        
        # Redis
        skopeo copy docker://docker.io/redis:latest docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/redis:latest
        
        # Golang
        skopeo copy docker://docker.io/golang:latest docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/golang:latest
        skopeo copy docker://docker.io/golang:1.18 docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/golang:1.18
        skopeo copy docker://docker.io/golang:1.21 docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/golang:1.21
        
        # alpine
        skopeo copy docker://docker.io/alpine:latest docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/alpine:latest
        
        # nodejs
        skopeo copy docker://docker.io/node:latest docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/node:latest
        skopeo copy docker://docker.io/node:16 docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/node:16
        skopeo copy docker://docker.io/node:20 docker://registry.cn-hangzhou.aliyuncs.com/jefferyjob/node:20
